"""initial

Revision ID: 0aa90d240f13
Revises:
Create Date: 2026-04-05 11:58:41.972469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0aa90d240f13"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("foo", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bills_id"), "bills", ["id"], unique=False)
    op.create_table(
        "sub_bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reference", sa.String(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sub_bills_bill_id_reference_ci",
        "sub_bills",
        ["bill_id", sa.literal_column("lower(reference)")],
        unique=True,
    )
    op.create_index(op.f("ix_sub_bills_id"), "sub_bills", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_bills_id"), table_name="sub_bills")
    op.drop_index("ix_sub_bills_bill_id_reference_ci", table_name="sub_bills")
    op.drop_table("sub_bills")
    op.drop_index(op.f("ix_bills_id"), table_name="bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
